services:
  easysmart_frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: "${VITE_API_URL}"
        VITE_PORT: "${VITE_PORT}"
        VITE_HOST: "${VITE_HOST}"
        VITE_ENABLE_CAPTCHA: "${VITE_ENABLE_CAPTCHA}"
        VITE_MODE: "${VITE_MODE}"
    container_name: easysmart_frontend
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - VITE_API_URL=${VITE_API_URL}
      - VITE_PORT=${VITE_PORT}
      - VITE_HOST=${VITE_HOST}
      - VITE_ENABLE_CAPTCHA=${VITE_ENABLE_CAPTCHA}
      - VITE_MODE=${VITE_MODE}
    ports:
      - "${VITE_PORT:-8002}:80"
    restart: always
    networks:
      - easysmart_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  easysmart_network:
    name: easysmart_network
    driver: bridge
